'use client';

import React, { createContext, useContext, useState, useCallback, useMemo, type ReactNode } from 'react';

export type LanguageCode = 
  | 'english' | 'hindi' | 'telugu' | 'tamil' | 'marathi' 
  | 'kannada' | 'bengali' | 'gujarati' | 'malayalam' | 'punjabi' | 'sanskrit';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  ttsLang: string; // Language code for Web Speech API
}

export const LANGUAGES: Language[] = [
  { code: 'english', name: 'English', nativeName: 'English', flag: 'EN', ttsLang: 'en-IN' },
  { code: 'hindi', name: 'Hindi', nativeName: 'हिन्दी', flag: 'HI', ttsLang: 'hi-IN' },
  { code: 'telugu', name: 'Telugu', nativeName: 'తెలుగు', flag: 'TE', ttsLang: 'te-IN' },
  { code: 'tamil', name: 'Tamil', nativeName: 'தமிழ்', flag: 'TA', ttsLang: 'ta-IN' },
  { code: 'marathi', name: 'Marathi', nativeName: 'मराठी', flag: 'MR', ttsLang: 'mr-IN' },
  { code: 'kannada', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: 'KN', ttsLang: 'kn-IN' },
  { code: 'bengali', name: 'Bengali', nativeName: 'বাংলা', flag: 'BN', ttsLang: 'bn-IN' },
  { code: 'gujarati', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: 'GU', ttsLang: 'gu-IN' },
  { code: 'malayalam', name: 'Malayalam', nativeName: 'മലയാളം', flag: 'ML', ttsLang: 'ml-IN' },
  { code: 'punjabi', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: 'PA', ttsLang: 'pa-IN' },
  { code: 'sanskrit', name: 'Sanskrit', nativeName: 'संस्कृतम्', flag: 'SA', ttsLang: 'hi-IN' },
];

// UI translations for the entire website
export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  english: {
    home: 'Home',
    chapters: '18 Chapters',
    allSlokas: 'All 700 Slokas',
    speakers: 'Speakers',
    search: 'Search slokas...',
    divineDarshan: 'Divine Darshan',
    speakersOfGita: 'Speakers of the Gita',
    featuredSloka: 'Featured Sloka',
    beginJourney: 'Begin Your Spiritual Journey',
    beginJourneyDesc: 'Let the timeless wisdom of the Gita guide you towards inner peace, clarity of purpose, and spiritual awakening.',
    startReading: 'Start Reading',
    readFullExplanation: 'Read Full Explanation',
    briefOverview: 'Brief Overview',
    simpleExplanation: 'Simple Explanation',
    detailedUnderstanding: 'Detailed Understanding',
    whyThisMatters: 'Why This Matters Today',
    practicalExample: 'Practical Example',
    motivationalTakeaway: 'Motivational Takeaway',
    listenSloka: 'Listen to this Sloka',
    translation: 'Translation',
    close: 'Close',
    clearFilters: 'Clear Filters',
    filter: 'Filter',
    slokasFound: 'slokas found',
    viewAllSlokas: 'View all slokas by',
    slokaDistribution: 'Sloka Distribution',
    selectLanguage: 'Select Language',
    krishna: 'Lord Krishna',
    arjuna: 'Arjuna',
    divineChariot: 'Divine Chariot',
    vishwaroop: 'Vishwaroop',
    exploreTopics: 'Explore by Topics',
    verses: 'verses',
    slokas: 'slokas',
  },
  hindi: {
    home: 'होम',
    chapters: '18 अध्याय',
    allSlokas: 'सभी 700 श्लोक',
    speakers: 'वक्ता',
    search: 'श्लोक खोजें...',
    divineDarshan: 'दिव्य दर्शन',
    speakersOfGita: 'गीता के वक्ता',
    featuredSloka: 'विशेष श्लोक',
    beginJourney: 'अपनी आध्यात्मिक यात्रा शुरू करें',
    beginJourneyDesc: 'गीता का कालातीत ज्ञान आपको आंतरिक शांति, उद्देश्य की स्पष्टता और आध्यात्मिक जागृति की ओर मार्गदर्शन करे।',
    startReading: 'पढ़ना शुरू करें',
    readFullExplanation: 'पूर्ण व्याख्या पढ़ें',
    briefOverview: 'संक्षिप्त विवरण',
    simpleExplanation: 'सरल व्याख्या',
    detailedUnderstanding: 'विस्तृत समझ',
    whyThisMatters: 'आज यह क्यों महत्वपूर्ण है',
    practicalExample: 'व्यावहारिक उदाहरण',
    motivationalTakeaway: 'प्रेरणादायक सार',
    listenSloka: 'यह श्लोक सुनें',
    translation: 'अनुवाद',
    close: 'बंद करें',
    clearFilters: 'फ़िल्टर साफ़ करें',
    filter: 'फ़िल्टर',
    slokasFound: 'श्लोक मिले',
    viewAllSlokas: 'के सभी श्लोक देखें',
    slokaDistribution: 'श्लोक वितरण',
    selectLanguage: 'भाषा चुनें',
    krishna: 'भगवान कृष्ण',
    arjuna: 'अर्जुन',
    divineChariot: 'दिव्य रथ',
    vishwaroop: 'विश्वरूप',
    exploreTopics: 'विषयों द्वारा अन्वेषण करें',
    verses: 'श्लोक',
    slokas: 'श्लोक',
  },
  telugu: {
    home: 'హోమ్',
    chapters: '18 అధ్యాయాలు',
    allSlokas: 'అన్ని 700 శ్లోకాలు',
    speakers: 'వక్తలు',
    search: 'శ్లోకాలు వెతకండి...',
    divineDarshan: 'దివ్య దర్శనం',
    speakersOfGita: 'గీత వక్తలు',
    featuredSloka: 'ప్రత్యేక శ్లోకం',
    beginJourney: 'మీ ఆధ్యాత్మిక ప్రయాణాన్ని ప్రారంభించండి',
    beginJourneyDesc: 'గీత యొక్క కాలాతీత జ్ఞానం మిమ్మల్ని అంతర్గత శాంతి, ప్రయోజనం యొక్క స్పష్టత మరియు ఆధ్యాత్మిక మేల్కొలుపు వైపు మార్గనిర్దేశం చేయనివ్వండి.',
    startReading: 'చదవడం ప్రారంభించండి',
    readFullExplanation: 'పూర్తి వివరణ చదవండి',
    briefOverview: 'సంక్షిప్త అవలోకనం',
    simpleExplanation: 'సరళ వివరణ',
    detailedUnderstanding: 'వివరమైన అవగాహన',
    whyThisMatters: 'ఇది ఈ రోజు ఎందుకు ముఖ్యం',
    practicalExample: 'ఆచరణాత్మక ఉదాహరణ',
    motivationalTakeaway: 'ప్రేరణాత్మక సారాంశం',
    listenSloka: 'ఈ శ్లోకం వినండి',
    translation: 'అనువాదం',
    close: 'మూసివేయి',
    clearFilters: 'ఫిల్టర్‌లను క్లియర్ చేయండి',
    filter: 'ఫిల్టర్',
    slokasFound: 'శ్లోకాలు కనుగొనబడ్డాయి',
    viewAllSlokas: 'యొక్క అన్ని శ్లోకాలు చూడండి',
    slokaDistribution: 'శ్లోక పంపిణీ',
    selectLanguage: 'భాష ఎంచుకోండి',
    krishna: 'శ్రీ కృష్ణుడు',
    arjuna: 'అర్జునుడు',
    divineChariot: 'దివ్య రథం',
    vishwaroop: 'విశ్వరూపం',
    exploreTopics: 'అంశాల ద్వారా అన్వేషించండి',
    verses: 'శ్లోకాలు',
    slokas: 'శ్లోకాలు',
  },
  tamil: {
    home: 'முகப்பு',
    chapters: '18 அத்தியாயங்கள்',
    allSlokas: 'அனைத்து 700 ஸ்லோகங்கள்',
    speakers: 'பேச்சாளர்கள்',
    search: 'ஸ்லோகங்களைத் தேடுங்கள்...',
    divineDarshan: 'தெய்வீக தரிசனம்',
    speakersOfGita: 'கீதையின் பேச்சாளர்கள்',
    featuredSloka: 'சிறப்பு ஸ்லோகம்',
    beginJourney: 'உங்கள் ஆன்மீக பயணத்தைத் தொடங்குங்கள்',
    beginJourneyDesc: 'கீதையின் காலமற்ற ஞானம் உங்களை உள் அமைதி, தெளிவான நோக்கம் மற்றும் ஆன்மீக விழிப்புணர்வை நோக்கி வழிநடத்தட்டும்.',
    startReading: 'படிக்கத் தொடங்குங்கள்',
    readFullExplanation: 'முழு விளக்கத்தைப் படியுங்கள்',
    briefOverview: 'சுருக்கமான கண்ணோட்டம்',
    simpleExplanation: 'எளிய விளக்கம்',
    detailedUnderstanding: 'விரிவான புரிதல்',
    whyThisMatters: 'இன்று இது ஏன் முக்கியம்',
    practicalExample: 'நடைமுறை உதாரணம்',
    motivationalTakeaway: 'ஊக்கமளிக்கும் சாரம்',
    listenSloka: 'இந்த ஸ்லோகத்தைக் கேளுங்கள்',
    translation: 'மொழிபெயர்ப்பு',
    close: 'மூடு',
    clearFilters: 'வடிகட்டிகளை அழி',
    filter: 'வடிகட்டி',
    slokasFound: 'ஸ்லோகங்கள் கண்டறியப்பட்டன',
    viewAllSlokas: 'இன் அனைத்து ஸ்லோகங்களையும் காண்க',
    slokaDistribution: 'ஸ்லோக விநியோகம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    krishna: 'ஸ்ரீ கிருஷ்ணர்',
    arjuna: 'அர்ஜுனன்',
    divineChariot: 'தெய்வீக தேர்',
    vishwaroop: 'விஸ்வரூபம்',
    exploreTopics: 'தலைப்புகள் மூலம் ஆராயுங்கள்',
    verses: 'வசனங்கள்',
    slokas: 'ஸ்லோகங்கள்',
  },
  marathi: {
    home: 'होम',
    chapters: '18 अध्याय',
    allSlokas: 'सर्व 700 श्लोक',
    speakers: 'वक्ते',
    search: 'श्लोक शोधा...',
    divineDarshan: 'दिव्य दर्शन',
    speakersOfGita: 'गीतेचे वक्ते',
    featuredSloka: 'विशेष श्लोक',
    beginJourney: 'तुमचा आध्यात्मिक प्रवास सुरू करा',
    beginJourneyDesc: 'गीतेचे कालातीत ज्ञान तुम्हाला आंतरिक शांती, उद्देशाची स्पष्टता आणि आध्यात्मिक जागृतीकडे मार्गदर्शन करू द्या.',
    startReading: 'वाचायला सुरुवात करा',
    readFullExplanation: 'संपूर्ण स्पष्टीकरण वाचा',
    briefOverview: 'संक्षिप्त विवरण',
    simpleExplanation: 'सोपे स्पष्टीकरण',
    detailedUnderstanding: 'विस्तृत समज',
    whyThisMatters: 'आज हे का महत्त्वाचे आहे',
    practicalExample: 'व्यावहारिक उदाहरण',
    motivationalTakeaway: 'प्रेरणादायी सार',
    listenSloka: 'हा श्लोक ऐका',
    translation: 'भाषांतर',
    close: 'बंद करा',
    clearFilters: 'फिल्टर साफ करा',
    filter: 'फिल्टर',
    slokasFound: 'श्लोक सापडले',
    viewAllSlokas: 'चे सर्व श्लोक पहा',
    slokaDistribution: 'श्लोक वितरण',
    selectLanguage: 'भाषा निवडा',
    krishna: 'भगवान श्रीकृष्ण',
    arjuna: 'अर्जुन',
    divineChariot: 'दिव्य रथ',
    vishwaroop: 'विश्वरूप',
    exploreTopics: 'विषयांनुसार अन्वेषण करा',
    verses: 'श्लोक',
    slokas: 'श्लोक',
  },
  kannada: {
    home: 'ಮುಖಪುಟ',
    chapters: '18 ಅಧ್ಯಾಯಗಳು',
    allSlokas: 'ಎಲ್ಲಾ 700 ಶ್ಲೋಕಗಳು',
    speakers: 'ಮಾತನಾಡುವವರು',
    search: 'ಶ್ಲೋಕಗಳನ್ನು ಹುಡುಕಿ...',
    divineDarshan: 'ದಿವ್ಯ ದರ್ಶನ',
    speakersOfGita: 'ಗೀತೆಯ ಮಾತನಾಡುವವರು',
    featuredSloka: 'ವಿಶೇಷ ಶ್ಲೋಕ',
    beginJourney: 'ನಿಮ್ಮ ಆಧ್ಯಾತ್ಮಿಕ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    beginJourneyDesc: 'ಗೀತೆಯ ಕಾಲಾತೀತ ಬುದ್ಧಿವಂತಿಕೆ ನಿಮ್ಮನ್ನು ಆಂತರಿಕ ಶಾಂತಿ, ಉದ್ದೇಶದ ಸ್ಪಷ್ಟತೆ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಎಚ್ಚರಿಕೆಯ ಕಡೆಗೆ ಮಾರ್ಗದರ್ಶನ ಮಾಡಲಿ.',
    startReading: 'ಓದಲು ಪ್ರಾರಂಭಿಸಿ',
    readFullExplanation: 'ಪೂರ್ಣ ವಿವರಣೆ ಓದಿ',
    briefOverview: 'ಸಂಕ್ಷಿಪ್ತ ಅವಲೋಕನ',
    simpleExplanation: 'ಸರಳ ವಿವರಣೆ',
    detailedUnderstanding: 'ವಿವರವಾದ ತಿಳುವಳಿಕೆ',
    whyThisMatters: 'ಇದು ಇಂದು ಏಕೆ ಮುಖ್ಯ',
    practicalExample: 'ಪ್ರಾಯೋಗಿಕ ಉದಾಹರಣೆ',
    motivationalTakeaway: 'ಪ್ರೇರಣಾದಾಯಕ ಸಾರಾಂಶ',
    listenSloka: 'ಈ ಶ್ಲೋಕವನ್ನು ಕೇಳಿ',
    translation: 'ಅನುವಾದ',
    close: 'ಮುಚ್ಚು',
    clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    filter: 'ಫಿಲ್ಟರ್',
    slokasFound: 'ಶ್ಲೋಕಗಳು ಕಂಡುಬಂದಿವೆ',
    viewAllSlokas: 'ರ ಎಲ್ಲಾ ಶ್ಲೋಕಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    slokaDistribution: 'ಶ್ಲೋಕ ವಿತರಣೆ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    krishna: 'ಶ್ರೀ ಕೃಷ್ಣ',
    arjuna: 'ಅರ್ಜುನ',
    divineChariot: 'ದಿವ್ಯ ರಥ',
    vishwaroop: 'ವಿಶ್ವರೂಪ',
    exploreTopics: 'ವಿಷಯಗಳ ಮೂಲಕ ಅನ್ವೇಷಿಸಿ',
    verses: 'ಶ್ಲೋಕಗಳು',
    slokas: 'ಶ್ಲೋಕಗಳು',
  },
  bengali: {
    home: 'হোম',
    chapters: '18 অধ্যায়',
    allSlokas: 'সমস্ত 700 শ্লোক',
    speakers: 'বক্তা',
    search: 'শ্লোক খুঁজুন...',
    divineDarshan: 'দিব্য দর্শন',
    speakersOfGita: 'গীতার বক্তা',
    featuredSloka: 'বিশেষ শ্লোক',
    beginJourney: 'আপনার আধ্যাত্মিক যাত্রা শুরু করুন',
    beginJourneyDesc: 'গীতার কালজয়ী জ্ঞান আপনাকে অন্তর্জ্ঞান শান্তি, উদ্দেশ্যের স্পষ্টতা এবং আধ্যাত্মিক জাগরণের দিকে পরিচালিত করুক।',
    startReading: 'পড়া শুরু করুন',
    readFullExplanation: 'সম্পূর্ণ ব্যাখ্যা পড়ুন',
    briefOverview: 'সংক্ষিপ্ত বিবরণ',
    simpleExplanation: 'সহজ ব্যাখ্যা',
    detailedUnderstanding: 'বিস্তারিত বোঝাপড়া',
    whyThisMatters: 'আজ এটি কেন গুরুত্বপূর্ণ',
    practicalExample: 'ব্যবহারিক উদাহরণ',
    motivationalTakeaway: 'অনুপ্রেরণামূলক সারাংশ',
    listenSloka: 'এই শ্লোক শুনুন',
    translation: 'অনুবাদ',
    close: 'বন্ধ করুন',
    clearFilters: 'ফিল্টার মুছুন',
    filter: 'ফিল্টার',
    slokasFound: 'শ্লোক পাওয়া গেছে',
    viewAllSlokas: 'র সমস্ত শ্লোক দেখুন',
    slokaDistribution: 'শ্লোক বিতরণ',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    krishna: 'শ্রী কৃষ্ণ',
    arjuna: 'অর্জুন',
    divineChariot: 'দিব্য রথ',
    vishwaroop: 'বিশ্বরূপ',
    exploreTopics: 'বিষয় অনুসারে অন্বেষণ করুন',
    verses: 'শ্লোক',
    slokas: 'শ্লোক',
  },
  gujarati: {
    home: 'હોમ',
    chapters: '18 અધ્યાય',
    allSlokas: 'બધા 700 શ્લોક',
    speakers: 'વક્તા',
    search: 'શ્લોક શોધો...',
    divineDarshan: 'દિવ્ય દર્શન',
    speakersOfGita: 'ગીતાના વક્તા',
    featuredSloka: 'વિશેષ શ્લોક',
    beginJourney: 'તમારી આધ્યાત્મિક યાત્રા શરૂ કરો',
    beginJourneyDesc: 'ગીતાનું કાલાતીત જ્ઞાન તમને આંતરિક શાંતિ, હેતુની સ્પષ્ટતા અને આધ્યાત્મિક જાગૃતિ તરફ માર્ગદર્શન આપે.',
    startReading: 'વાંચવાનું શરૂ કરો',
    readFullExplanation: 'સંપૂર્ણ સમજૂતી વાંચો',
    briefOverview: 'સંક્ષિપ્ત વિહંગાવલોકન',
    simpleExplanation: 'સરળ સમજૂતી',
    detailedUnderstanding: 'વિગતવાર સમજ',
    whyThisMatters: 'આજે આ શા માટે મહત્વપૂર્ણ છે',
    practicalExample: 'વ્યવહારિક ઉદાહરણ',
    motivationalTakeaway: 'પ્રેરણાદાયી સાર',
    listenSloka: 'આ શ્લોક સાંભળો',
    translation: 'અનુવાદ',
    close: 'બંધ કરો',
    clearFilters: 'ફિલ્ટર સાફ કરો',
    filter: 'ફિલ્ટર',
    slokasFound: 'શ્લોક મળ્યા',
    viewAllSlokas: 'ના બધા શ્લોક જુઓ',
    slokaDistribution: 'શ્લોક વિતરણ',
    selectLanguage: 'ભાષા પસંદ કરો',
    krishna: 'શ્રી કૃષ્ણ',
    arjuna: 'અર્જુન',
    divineChariot: 'દિવ્ય રથ',
    vishwaroop: 'વિશ્વરૂપ',
    exploreTopics: 'વિષયો દ્વારા અન્વેષણ કરો',
    verses: 'શ્લોક',
    slokas: 'શ્લોક',
  },
  malayalam: {
    home: 'ഹോം',
    chapters: '18 അധ്യായങ്ങൾ',
    allSlokas: 'എല്ലാ 700 ശ്ലോകങ്ങളും',
    speakers: 'വക്താക്കൾ',
    search: 'ശ്ലോകങ്ങൾ തിരയുക...',
    divineDarshan: 'ദിവ്യ ദർശനം',
    speakersOfGita: 'ഗീതയിലെ വക്താക്കൾ',
    featuredSloka: 'പ്രത്യേക ശ്ലോകം',
    beginJourney: 'നിങ്ങളുടെ ആത്മീയ യാത്ര ആരംഭിക്കുക',
    beginJourneyDesc: 'ഗീതയുടെ കാലാതീത ജ്ഞാനം നിങ്ങളെ ആന്തരിക സമാധാനം, ഉദ്ദേശ്യത്തിന്റെ വ്യക്തത, ആത്മീയ ഉണർവ് എന്നിവയിലേക്ക് നയിക്കട്ടെ.',
    startReading: 'വായിക്കാൻ തുടങ്ങുക',
    readFullExplanation: 'പൂർണ്ണ വിശദീകരണം വായിക്കുക',
    briefOverview: 'ചുരുക്കമായ അവലോകനം',
    simpleExplanation: 'ലളിതമായ വിശദീകരണം',
    detailedUnderstanding: 'വിശദമായ ധാരണ',
    whyThisMatters: 'ഇന്ന് ഇത് എന്തുകൊണ്ട് പ്രധാനമാണ്',
    practicalExample: 'പ്രായോഗിക ഉദാഹരണം',
    motivationalTakeaway: 'പ്രചോദനാത്മക സാരാംശം',
    listenSloka: 'ഈ ശ്ലോകം കേൾക്കുക',
    translation: 'വിവർത്തനം',
    close: 'അടയ്ക്കുക',
    clearFilters: 'ഫിൽട്ടറുകൾ മായ്ക്കുക',
    filter: 'ഫിൽട്ടർ',
    slokasFound: 'ശ്ലോകങ്ങൾ കണ്ടെത്തി',
    viewAllSlokas: 'ന്റെ എല്ലാ ശ്ലോകങ്ങളും കാണുക',
    slokaDistribution: 'ശ്ലോക വിതരണം',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    krishna: 'ശ്രീ കൃഷ്ണൻ',
    arjuna: 'അർജ്ജുനൻ',
    divineChariot: 'ദിവ്യ രഥം',
    vishwaroop: 'വിശ്വരൂപം',
    exploreTopics: 'വിഷയങ്ങൾ പ്രകാരം പര്യവേക്ഷണം ചെയ്യുക',
    verses: 'ശ്ലോകങ്ങൾ',
    slokas: 'ശ്ലോകങ്ങൾ',
  },
  punjabi: {
    home: 'ਹੋਮ',
    chapters: '18 ਅਧਿਆਏ',
    allSlokas: 'ਸਾਰੇ 700 ਸ਼ਲੋਕ',
    speakers: 'ਬੁਲਾਰੇ',
    search: 'ਸ਼ਲੋਕ ਖੋਜੋ...',
    divineDarshan: 'ਦਿਵਯ ਦਰਸ਼ਨ',
    speakersOfGita: 'ਗੀਤਾ ਦੇ ਬੁਲਾਰੇ',
    featuredSloka: 'ਵਿਸ਼ੇਸ਼ ਸ਼ਲੋਕ',
    beginJourney: 'ਆਪਣੀ ਅਧਿਆਤਮਿਕ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    beginJourneyDesc: 'ਗੀਤਾ ਦਾ ਕਾਲਾਤੀਤ ਗਿਆਨ ਤੁਹਾਨੂੰ ਅੰਦਰੂਨੀ ਸ਼ਾਂਤੀ, ਉਦੇਸ਼ ਦੀ ਸਪੱਸ਼ਟਤਾ ਅਤੇ ਅਧਿਆਤਮਿਕ ਜਾਗ੍ਰਿਤੀ ਵੱਲ ਮਾਰਗਦਰਸ਼ਨ ਕਰੇ।',
    startReading: 'ਪੜ੍ਹਨਾ ਸ਼ੁਰੂ ਕਰੋ',
    readFullExplanation: 'ਪੂਰੀ ਵਿਆਖਿਆ ਪੜ੍ਹੋ',
    briefOverview: 'ਸੰਖੇਪ ਵੇਰਵਾ',
    simpleExplanation: 'ਸਰਲ ਵਿਆਖਿਆ',
    detailedUnderstanding: 'ਵਿਸਤਾਰਤ ਸਮਝ',
    whyThisMatters: 'ਅੱਜ ਇਹ ਮਹੱਤਵਪੂਰਨ ਕਿਉਂ ਹੈ',
    practicalExample: 'ਵਿਹਾਰਕ ਉਦਾਹਰਣ',
    motivationalTakeaway: 'ਪ੍ਰੇਰਣਾਦਾਇਕ ਸਾਰ',
    listenSloka: 'ਇਹ ਸ਼ਲੋਕ ਸੁਣੋ',
    translation: 'ਅਨੁਵਾਦ',
    close: 'ਬੰਦ ਕਰੋ',
    clearFilters: 'ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ',
    filter: 'ਫਿਲਟਰ',
    slokasFound: 'ਸ਼ਲੋਕ ਮਿਲੇ',
    viewAllSlokas: 'ਦੇ ਸਾਰੇ ਸ਼ਲੋਕ ਵੇਖੋ',
    slokaDistribution: 'ਸ਼ਲੋਕ ਵੰਡ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    krishna: 'ਸ਼੍ਰੀ ਕ੍ਰਿਸ਼ਨ',
    arjuna: 'ਅਰਜੁਨ',
    divineChariot: 'ਦਿਵਯ ਰੱਥ',
    vishwaroop: 'ਵਿਸ਼ਵਰੂਪ',
    exploreTopics: 'ਵਿਸ਼ਿਆਂ ਅਨੁਸਾਰ ਖੋਜੋ',
    verses: 'ਸ਼ਲੋਕ',
    slokas: 'ਸ਼ਲੋਕ',
  },
  sanskrit: {
    home: 'गृहम्',
    chapters: '18 अध्यायाः',
    allSlokas: 'सर्वे 700 श्लोकाः',
    speakers: 'वक्तारः',
    search: 'श्लोकान् अन्विष्य...',
    divineDarshan: 'दिव्यदर्शनम्',
    speakersOfGita: 'गीतायाः वक्तारः',
    featuredSloka: 'विशेषः श्लोकः',
    beginJourney: 'भवतः आध्यात्मिकं यात्रां आरभत',
    beginJourneyDesc: 'गीतायाः कालातीतं ज्ञानं भवन्तं आन्तरिकशान्तिं प्रति मार्गदर्शनं करोतु।',
    startReading: 'पठनम् आरभत',
    readFullExplanation: 'पूर्णं व्याख्यानं पठत',
    briefOverview: 'संक्षिप्तं विवरणम्',
    simpleExplanation: 'सरलं व्याख्यानम्',
    detailedUnderstanding: 'विस्तृता बोधः',
    whyThisMatters: 'अद्य इदं किमर्थं महत्त्वपूर्णम्',
    practicalExample: 'व्यावहारिकं उदाहरणम्',
    motivationalTakeaway: 'प्रेरणादायकं सारम्',
    listenSloka: 'इमं श्लोकं शृणोतु',
    translation: 'अनुवादः',
    close: 'पिधत्तु',
    clearFilters: 'फिल्टरान् निर्मलं कुरुत',
    filter: 'फिल्टर',
    slokasFound: 'श्लोकाः प्राप्ताः',
    viewAllSlokas: 'सर्वान् श्लोकान् पश्यतु',
    slokaDistribution: 'श्लोकवितरणम्',
    selectLanguage: 'भाषां चिनोतु',
    krishna: 'भगवान् श्रीकृष्णः',
    arjuna: 'अर्जुनः',
    divineChariot: 'दिव्यरथः',
    vishwaroop: 'विश्वरूपम्',
    exploreTopics: 'विषयैः अन्वेषणं कुरुत',
    verses: 'श्लोकाः',
    slokas: 'श्लोकाः',
  },
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setCurrentLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languages: Language[];
  getCurrentLanguage: () => Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<LanguageCode>('english');

  const t = useCallback((key: string): string => {
    return UI_TRANSLATIONS[currentLanguage]?.[key] || UI_TRANSLATIONS.english[key] || key;
  }, [currentLanguage]);

  const getCurrentLanguage = useCallback((): Language => {
    return LANGUAGES.find(l => l.code === currentLanguage) || LANGUAGES[0];
  }, [currentLanguage]);

  const value = useMemo(() => ({
    currentLanguage,
    setCurrentLanguage,
    t,
    languages: LANGUAGES,
    getCurrentLanguage,
  }), [currentLanguage, t, getCurrentLanguage]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
